package com.dhy.seismic2.daos.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dhy.seismic2.daos.bean.CarInfoModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CARITEM".
*/
public class CarInfoModelDao extends AbstractDao<CarInfoModel, String> {

    public static final String TABLENAME = "CARITEM";

    /**
     * Properties of entity CarInfoModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ID = new Property(0, String.class, "ID", true, "ID");
        public final static Property CARNUMBER = new Property(1, String.class, "CARNUMBER", false, "CARNUMBER");
        public final static Property USERNAME = new Property(2, String.class, "USERNAME", false, "USERNAME");
        public final static Property STATE = new Property(3, int.class, "STATE", false, "STATE");
    }


    public CarInfoModelDao(DaoConfig config) {
        super(config);
    }
    
    public CarInfoModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CARITEM\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: ID
                "\"CARNUMBER\" TEXT," + // 1: CARNUMBER
                "\"USERNAME\" TEXT," + // 2: USERNAME
                "\"STATE\" INTEGER NOT NULL );"); // 3: STATE
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CARITEM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CarInfoModel entity) {
        stmt.clearBindings();
 
        String ID = entity.getID();
        if (ID != null) {
            stmt.bindString(1, ID);
        }
 
        String CARNUMBER = entity.getCARNUMBER();
        if (CARNUMBER != null) {
            stmt.bindString(2, CARNUMBER);
        }
 
        String USERNAME = entity.getUSERNAME();
        if (USERNAME != null) {
            stmt.bindString(3, USERNAME);
        }
        stmt.bindLong(4, entity.getSTATE());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CarInfoModel entity) {
        stmt.clearBindings();
 
        String ID = entity.getID();
        if (ID != null) {
            stmt.bindString(1, ID);
        }
 
        String CARNUMBER = entity.getCARNUMBER();
        if (CARNUMBER != null) {
            stmt.bindString(2, CARNUMBER);
        }
 
        String USERNAME = entity.getUSERNAME();
        if (USERNAME != null) {
            stmt.bindString(3, USERNAME);
        }
        stmt.bindLong(4, entity.getSTATE());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public CarInfoModel readEntity(Cursor cursor, int offset) {
        CarInfoModel entity = new CarInfoModel( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // ID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // CARNUMBER
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // USERNAME
            cursor.getInt(offset + 3) // STATE
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CarInfoModel entity, int offset) {
        entity.setID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setCARNUMBER(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUSERNAME(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSTATE(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final String updateKeyAfterInsert(CarInfoModel entity, long rowId) {
        return entity.getID();
    }
    
    @Override
    public String getKey(CarInfoModel entity) {
        if(entity != null) {
            return entity.getID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CarInfoModel entity) {
        return entity.getID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
