package com.dhy.seismic2.daos.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dhy.seismic2.daos.bean.SyncDataFlagModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LocalSyncDataFlag".
*/
public class SyncDataFlagModelDao extends AbstractDao<SyncDataFlagModel, Integer> {

    public static final String TABLENAME = "LocalSyncDataFlag";

    /**
     * Properties of entity SyncDataFlagModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, int.class, "Id", true, "ID");
        public final static Property EVENTIDS = new Property(1, String.class, "EVENTIDS", false, "EVENTIDS");
    }


    public SyncDataFlagModelDao(DaoConfig config) {
        super(config);
    }
    
    public SyncDataFlagModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LocalSyncDataFlag\" (" + //
                "\"ID\" INTEGER PRIMARY KEY NOT NULL ," + // 0: Id
                "\"EVENTIDS\" TEXT);"); // 1: EVENTIDS
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LocalSyncDataFlag\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SyncDataFlagModel entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String EVENTIDS = entity.getEVENTIDS();
        if (EVENTIDS != null) {
            stmt.bindString(2, EVENTIDS);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SyncDataFlagModel entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String EVENTIDS = entity.getEVENTIDS();
        if (EVENTIDS != null) {
            stmt.bindString(2, EVENTIDS);
        }
    }

    @Override
    public Integer readKey(Cursor cursor, int offset) {
        return cursor.getInt(offset + 0);
    }    

    @Override
    public SyncDataFlagModel readEntity(Cursor cursor, int offset) {
        SyncDataFlagModel entity = new SyncDataFlagModel( //
            cursor.getInt(offset + 0), // Id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // EVENTIDS
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SyncDataFlagModel entity, int offset) {
        entity.setId(cursor.getInt(offset + 0));
        entity.setEVENTIDS(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Integer updateKeyAfterInsert(SyncDataFlagModel entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public Integer getKey(SyncDataFlagModel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SyncDataFlagModel entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
