package com.dhy.seismic2.daos.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dhy.seismic2.daos.bean.UserIdModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_ID_MODEL".
*/
public class UserIdModelDao extends AbstractDao<UserIdModel, String> {

    public static final String TABLENAME = "USER_ID_MODEL";

    /**
     * Properties of entity UserIdModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property USERID = new Property(0, String.class, "USERID", true, "USERID");
        public final static Property STATE = new Property(1, int.class, "STATE", false, "STATE");
    }


    public UserIdModelDao(DaoConfig config) {
        super(config);
    }
    
    public UserIdModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_ID_MODEL\" (" + //
                "\"USERID\" TEXT PRIMARY KEY NOT NULL ," + // 0: USERID
                "\"STATE\" INTEGER NOT NULL );"); // 1: STATE
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_ID_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserIdModel entity) {
        stmt.clearBindings();
 
        String USERID = entity.getUSERID();
        if (USERID != null) {
            stmt.bindString(1, USERID);
        }
        stmt.bindLong(2, entity.getSTATE());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserIdModel entity) {
        stmt.clearBindings();
 
        String USERID = entity.getUSERID();
        if (USERID != null) {
            stmt.bindString(1, USERID);
        }
        stmt.bindLong(2, entity.getSTATE());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public UserIdModel readEntity(Cursor cursor, int offset) {
        UserIdModel entity = new UserIdModel( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // USERID
            cursor.getInt(offset + 1) // STATE
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserIdModel entity, int offset) {
        entity.setUSERID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setSTATE(cursor.getInt(offset + 1));
     }
    
    @Override
    protected final String updateKeyAfterInsert(UserIdModel entity, long rowId) {
        return entity.getUSERID();
    }
    
    @Override
    public String getKey(UserIdModel entity) {
        if(entity != null) {
            return entity.getUSERID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserIdModel entity) {
        return entity.getUSERID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
